// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tanulok;

namespace Tanulok.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tanulok.SzervezetiEgyseg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SZeNev")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("SZeNev")
                        .IsUnique();

                    b.ToTable("SzervezetiEgysegek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SZeNev = "Műszaki és Informatikai Kar"
                        },
                        new
                        {
                            Id = 2,
                            SZeNev = "Gazdaságtudományi Kar"
                        },
                        new
                        {
                            Id = 3,
                            SZeNev = "Kertészeti és Vidékfejlesztési Kar"
                        });
                });

            modelBuilder.Entity("Tanulok.Tagozat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TagozatNev")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("TagozatNev")
                        .IsUnique();

                    b.ToTable("Tagozatok");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagozatNev = "Nappali"
                        },
                        new
                        {
                            Id = 2,
                            TagozatNev = "Levelező"
                        });
                });

            modelBuilder.Entity("Tanulok.Tanulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AktualFelev")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("FelvetelDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NEPTUNKod")
                        .IsRequired()
                        .HasColumnType("varchar(6) CHARACTER SET utf8mb4")
                        .HasMaxLength(6);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<int>("SzervezetiEgysegId")
                        .HasColumnType("int");

                    b.Property<int>("TagozatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NEPTUNKod")
                        .IsUnique();

                    b.HasIndex("SzervezetiEgysegId");

                    b.HasIndex("TagozatId");

                    b.ToTable("Tanulok");
                });

            modelBuilder.Entity("Tanulok.Tanulo", b =>
                {
                    b.HasOne("Tanulok.SzervezetiEgyseg", "SzervezetiEgyseg")
                        .WithMany()
                        .HasForeignKey("SzervezetiEgysegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tanulok.Tagozat", "Tagozat")
                        .WithMany()
                        .HasForeignKey("TagozatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
